### PR TITLE
Fix radial solver (?)

### PR DESCRIPTION
**Pull request by vongostev**
Hi Sébastien,

I tried to fix the radial solver that didn't work for me. My changes are:
1. I removed the naive recursion algorithm from `binary_search` and used [scipy.optimize.bisect](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html#scipy.optimize.bisect) that has the same performance and functions. After that, the solver began to work correctly but the mode profiles were weird: the field had a big growth close to corners of the grid.
2. I decreased r_max from `indexProfile.areaSize` to `max(indexProfile.R)` because values greater than max(indexProfile.R) are incorrect on the given grid. So I removed line 200 as it became meaningless. 
3. I assumed to zero of the radial field component on points where `r > a * min_radius_bc` to remove the field growth to grid corners. I understand that it is a monkey patch but I don't understand why profiles demonstrate this behavior in corners while the field is correct in the center of the grid.
4. Also I fixed README :)

The code works correctly with the given examples. If you have more complicated tests, please use them to verify my changes.

### CODE REVIEW

**Comment by wavefrontshaping** [comment]
Hi,

Thanks for the work.
I will need some time to review the changes (it is also a bit more difficult where there are both style changes and algorithmic ones in the same commits).
Point 3. is a bummer, as it means there is something very wrong somewhere.
By the way, I still do not understand what was and what caused the error you had with the original code.

**Comment by vongostev** [comment]
Hi,
There are no style changes here. When I edited the code, Spyder made autoformatting with autopep8, but I reverted it. So, the first two commits returned the code to the original state. Sorry for that. 

The last commit is only about algorithmic changes.

**Comment by wavefrontshaping** [comment]
>  After that, the solver began to work correctly but the mode profiles were weird: the field had a big growth close to corners of the grid.

I do not know what to do with that pull request. You say it works but the profiles are weird. Well, that means it does not really work, does it?
As I cannot reproduce your error, can you tell me more about it? Which loop runs in infinite loop? What do you mean by constant value in line 216?

**Comment by wavefrontshaping** [comment]
I tried the code with bisect instead of my own code, it seems to work the same for me, no " big growth close to corners of the grid".
Could you provide me with an example that fails?

**Comment by vongostev** [comment]
Hi, I used this code to test it.
```python
import pyMMF
import numpy as np
import matplotlib.pyplot as plt

# Parameters
NA = 0.2
radius = 25.  # in microns
# calculate the field on an area larger than the diameter of the fiber
areaSize = 3.5*radius
npoints = 2**8  # resolution of the window
n1 = 1.472
wl = 0.678  # wavelength in microns


profile = pyMMF.IndexProfile(npoints=npoints, areaSize=areaSize)

# Initialize the index profile
# profile.initStepIndex(n1=n1, a=radius, NA=NA)
profile.initParabolicGRIN(n1=n1, a=radius, NA=NA)
# Instantiate the solver
solver = pyMMF.propagationModeSolver()
# Set the profile to the solver
solver.setIndexProfile(profile)
# Set the wavelength
solver.setWL(wl)
# Estimate the number of modes for a graded index fiber
Nmodes_estim = pyMMF.estimateNumModesSI(wl, radius, NA, pola=1)

print(f"Estimated number of modes using the V number = {Nmodes_estim}")

modes = solver.solve(mode='radial',
                     propag_only=True,
                     N_beta_coarse=int(1e3),
                     curvature=None)

fig, axes = plt.subplots(5, 5, figsize=(10, 10))
for i, ax in enumerate(np.ravel(axes)):
    try:
        field = modes.profiles[i].reshape([npoints]*2)
        ax.imshow(np.log10(np.abs(field)))
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_xticklabels([])
        ax.set_yticklabels([])
    except:
        continue
plt.show()
```
Dependencies have these versions:
```
Windows 10 20H2
matplotlib 3.3.4
numpy 1.20.2
numba 0.52.2
scipy 1.6.2
```
Which versions of these libraries do you use?

> I do not know what to do with that pull request. You say it works but the profiles are weird.

I meant that the algorithm finishes with any result, not with "recursion depth exceeded" error.

> As I cannot reproduce your error, can you tell me more about it? Which loop runs in infinite loop? What do you mean by constant value in line 216?

I archieved "recursion depth exceeded" error in the [line 219](https://github.com/wavefrontshaping/pyMMF/blob/3488e86a86deabaf9d207e0abd2d27a78b3adf6c/pyMMF/solvers/radial.py#L219). After step-by-step analysis I understood that the problem was in the `binary_search` function. In this function the condition in the [line 127](https://github.com/wavefrontshaping/pyMMF/blob/3488e86a86deabaf9d207e0abd2d27a78b3adf6c/pyMMF/solvers/radial.py#L127) was always false and the function didn't return anything. After the replacing your own code by `scipy.optimize.bisect` this error was gone, but profiles I obtained were weird.

I think there is a dependencies mismatching. If you use specific versions of these libraries, please, tell me which ones.

**Comment by vongostev** [comment]
Hi Sébastien!

I made SI solver so much faster. You can see the performance comparison in [pymmf_performance.ipynb](https://github.com/vongostev/pyMMF/blob/37fff892781b82bba5ac859d3df845bb923233ee/example/pymmf_performance.ipynb).

I removed duplicated code and used joblib to one-line orchestration. Mode profiles are the same as in the old version of pyMMF.

**Comment by wavefrontshaping** [comment]
Hi,

Thanks for the work.
However, I tried your code and I indeed have huge values around the corners.

I tried with this code that we used in our recent paper [Generate_modes.ipynb](https://github.com/wavefrontshaping/article_MMF_disorder/blob/main/Generate_theoretical_modes/Generate_modes.ipynb)

It generates the figures for the profiles of the modes, and the ones with your code are wrong.

There is something wrong with the boundary condition. The loop is supposed to stop when the field "far away" from the center is close to 0. It is obviously not the case here. Either the boundary condition has changed, or the algorithm condition to stop is wrong. 

It needs to be investigated, but I appreciate the speed of your version of the algorithm!

**Comment by wavefrontshaping** [comment]
It seems that `bisect` does not work.
It is supposed to minimize the function `func_fast` but if you print the result of `func_fast(beta)` for the beta value found by `bisect`, this value is of the order of 1.
The solutions look ok because they always do due to phase symmetries, but, at least for this example, they are just wrong.
I do not understand why `bisect` does not work...

**Comment by vongostev** [comment]
Hi,

It looks like that there is a convergency problem of the second-order differences method from the article 
Lakshman S. Tamil, S. S. Mitra, R. Dutta, and J. M. T. Pereira,  "Finite difference solution for graded-index cylindrical dielectric waveguides:  a scalar wave approximation"

I obtained much better results with using of parameters in meters, not micrometers, for example:
```NA = 0.2
radius = 25e-6
areaSize = 2.4*radius
npoints = 2**8
n1 = 1.45
wl = 1.55e-6
```
It is a equivalent set of parameters to the presented one in [your article materials](https://github.com/wavefrontshaping/article_MMF_disorder/blob/main/Generate_theoretical_modes/Generate_modes.ipynb) but in meters.

Modes profiles with parameters in meters.___________________________________ Modes profiles with parameters in microns

**Comment by vongostev** [comment]
I made a big update. Now the example calculates correctly, but if a decrease `wl` to `0.632 nm` the results became bad. I think that is really a convergency problem dependent from the ratio `wl / radius`. I'm trying to solve this.

**Comment by wavefrontshaping** [comment]
Did you find the source of the convergence issue?

I am trying to add unit tests to systematically compare results when new modifications are introduced to results obtained on a test case.
Your new implementation did much better than before, but still fails the test, I have differences of the order of a few percents on some modes. The error is still located in the corners, indicating a convergence issue as the boundary condition for large radiuses is not satisfied. 

Here is an example:
diff

I do not know yet which one did not converge as much as the other one, I will try to compare to FDTD simulations with Comsol to see which one is best. 

I am sorry to take so much time to add your modifications, but I have to be extra careful as a part of my work relies on these simulations,

**Pull request merged**
